"""Add decision field to Bid model

Revision ID: 872e9c84e6c4
Revises: e23bf2f8ca11
Create Date: 2024-10-01 16:50:31.796727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '872e9c84e6c4'
down_revision = 'e23bf2f8ca11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decision', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bid', schema=None) as batch_op:
        batch_op.drop_column('decision')

    # ### end Alembic commands ###
