"""Add submitted_on field to Bid model

Revision ID: e23bf2f8ca11
Revises: 0a983114a3f9
Create Date: 2024-10-01 16:39:06.627866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e23bf2f8ca11'
down_revision = '0a983114a3f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_on', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bid', schema=None) as batch_op:
        batch_op.drop_column('submitted_on')

    # ### end Alembic commands ###
